### ISSUE TITLE
Ad revenue events will not be included in global events

### ISSUE THREAD

**Issue by ErkFu** [singular-labs/Singular-Unity-SDK#5]
In my app I have set up the global events correctly and I manually initialize singular after setting it up。
**`   bool result = SingularSDK.SetGlobalProperty("app version", Application.version, true);
    SingularSDK.InitializeSingularSDK();`**

Events uploaded by **SingularSDK.Event** interface will carry global events，it worked well, but events uploaded by **SingularSDK.AdRevenue** will not carry global events. These two events are handled differently in Singular SDK.

**Comment by nursingular** [comment]
Hi @ErkFu , Thank you for reporting this issue!
We resolved it in the current version: `5.1.3`
Feel free to upgrade to 5.1.3 and let us know if it helps.
Thanks,

**Comment by ErkFu** [comment]
The 5.1.3 SDK works fine now. Thanks

**Comment by ErkFu** [comment]
> Hi @ErkFu , Thank you for reporting this issue! We resolved it in the current version: `5.1.3` Feel free to upgrade to 5.1.3 and let us know if it helps. Thanks,

The 5.1.3 SDK works fine now. Thanks
